---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: peer0.org1.example.com
  name: peer0.org1.example.com
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: peer0.org1.example.com
  template:
    metadata:
      labels:
        app: peer0.org1.example.com
    spec:
      serviceAccountName: peer
      containers:
      - image: postfinance/hlfabric-k8scc:2.1.1-k8scc0.0.4
        name: fabric-peer
        workingDir: /etc/hyperledger/fabric/
        env:
        - name: FABRIC_LOGGING_SPEC
          value: "DEBUG:msp.identity=INFO"
        - name: CORE_PEER_ADDRESS
          value: "peer0-org1-example-com:7051"
        - name: CORE_PEER_LISTENADDRESS
          value: "0.0.0.0:7051"
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: "0.0.0.0:7052"
        - name: CORE_PEER_LOCALMSPID
          value: "Org1MSP"
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: K8SCC_CFGFILE
          value: "/opt/k8scc/k8scc.yaml"
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric/
          name: core
        - mountPath: /var/lib/k8scc/transfer/
          name: transfer-pv
        - mountPath: /var/hyperledger/production/
          name: peer
        - mountPath: /etc/hyperledger/fabric/msp/
          subPath: organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/
          name: fabric-config
        - mountPath: /etc/hyperledger/fabric/tls/
          subPath: organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/
          name: fabric-config
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 9443
        resources:
          limits:
            cpu: "200m"
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9443
          initialDelaySeconds: 2
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 10
      volumes:
      - name: core
        configMap:
          name: core
      - name: fabric-config
        persistentVolumeClaim:
          claimName: fabric-config
      - name: transfer-pv
        persistentVolumeClaim:
          claimName: k8scc-transfer-pv
      - name: peer
        persistentVolumeClaim:
          claimName: peer0.org1.example.com
---
kind: Service
apiVersion: v1
metadata:
  name: peer0-org1-example-com
spec:
  selector:
    app: "peer0.org1.example.com"
  ports:
  - name: "grpc"
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: "chaincode"
    port: 7052
    protocol: TCP
    targetPort: 7052
  - name: "ops"
    port: 9443
    protocol: TCP
    targetPort: 9443
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0.org1.example.com
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
